---
- name: deploy the spring petclinic
  hosts: all
  become: yes
  vars: 
    Build_file: '/tmp/spring-petclinic-3.0.0-SNAPSHOT.jar'
  tasks: 
    - name: get the jar file
      ansible.builtin.get_url:
        url: "{{Build_file}}"
        dest: "/opt/spring-petclinic-2.7.3.jar"
    - name: copy the spc.service
      ansible.builtin.copy: 
        src: spc.service
        dest: /etc/systemd/system/spc.service
    - name: service file
      ansible.builtin.file:
        path: /etc/systemd/system/spc.service
        mode: '0644'
        state: file
    - name: enable and start spc.service
      ansible.builtin.systemd:
        name: spc.service
        enabled: true
        state: started
